---
# Source: postgres/templates/secret.yaml
apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret

type: Opaque

data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  POSTGRES_DB: ZmFybWRi
---
# Source: postgres/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi
---
# Source: postgres/templates/service.yaml
apiVersion: v1
kind: Service

metadata:
  name: postgres-service

spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432

  type: ClusterIP
---
# Source: postgres/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:

        - name: postgres

          image: "postgres:17"

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          resources:
            requests:
              memory: 256Mi
              cpu: 100m

            limits:
              memory: 512Mi
              cpu: 500m

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
