replicaCount: 3

image:
  repository: arjunmj/farm-stack
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: 128Mi
    cpu: 100m

  limits:
    memory: 256Mi
    cpu: 500m

config:
  appName: Farm Inventory
  environment: Development
  company: Amjmax Solutions

database:
  host: postgres-service
  port: "5432"
  name: farmdb

initContainer:
  enabled: true

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0 

secret:
  dbUser: postgres
  dbPassword: postgres123

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: farm-service-account

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30080

rbac:
  roleName: farm-role
  roleBindingName: farm-rolebinding

probes:

  startup:
    enabled: true
    path: /health
    port: 8000
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 12

  readiness:
    enabled: true
    path: /health
    port: 8000
    initialDelaySeconds: 5
    periodSeconds: 5

  liveness:
    enabled: true
    path: /health
    port: 8000
    initialDelaySeconds: 15
    periodSeconds: 10

ingress:
  enabled: true

  className: traefik

  host: farm-inventory.local

  path: /

  pathType: Prefix

hpa:
  enabled: true

  minReplicas: 3
  maxReplicas: 6

  cpuUtilization: 70

  scaleUp:
    stabilizationWindowSeconds: 0

    policy:
      type: Percent
      value: 100
      periodSeconds: 15

  scaleDown:
    stabilizationWindowSeconds: 60

    policy:
      type: Percent
      value: 50
      periodSeconds: 60
  
pdb:
  enabled: true
  maxUnavailable: 1

monitoring:
  enabled: true
  
blueGreen:
  enabled: true

  activeColor: blue

  blue:
    enabled: true
    imageTag: "35"

  green:
    enabled: true
    imageTag: "34"
