kube-prometheus-stack:

  grafana:

    adminPassword: admin123

    service:
      type: NodePort

    ingress:
      enabled: true
      ingressClassName: traefik

      hosts:
        - grafana.local

      path: /
      pathType: Prefix

  prometheus:

    prometheusSpec:
      retention: 7d

  alertmanager:
    enabled: true