kube-prometheus-stack:

  grafana:

    adminPassword: admin123

    service:
      type: NodePort

    ingress:
      enabled: true
      ingressClassName: traefik

      hosts:
        - grafana.local

      path: /
      pathType: Prefix

  prometheus:

    prometheusSpec:
      retention: 7d

    ingress:
      enabled: true

      ingressClassName: traefik
      hosts:
        - prometheus.local
      paths:
        - /
      pathType: Prefix

  alertmanager:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - alertmanager.local
      paths:
        - /
      pathType: prefix
  
