apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: farm-test-alert
  namespace: monitoring

spec:
  groups:
  - name: farm-test

    rules:

    - alert: FarmInventoryAlwaysFiring

      expr: vector(1)

      for: 30s

      labels:
        severity: warning

      annotations:
        summary: Farm Inventory Test Alert
        description: Alertmanager email delivery test