apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: email-test
  namespace: monitoring
  labels:
    release: monitoring-stack

spec:
  groups:
  - name: email-test
    rules:
    - alert: EmailTestAlert
      expr: vector(1)
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: Email Test Alert
        description: Alertmanager email delivery test