apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-inventory
  namespace: farm
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: farm-inventory
  template:
    metadata:
      labels:
        app: farm-inventory
    spec:
      containers:
        - name: farm-inventory
          image: arjunmj/farm-inventory:latest
          imagePullPolicy: Always

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          
          
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: APP_NAME
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: ENVIRONMENT
            - name: COMPANY
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: COMPANY
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: DB_PORT      
            
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: DB_NAME
            
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: farm-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: farm-secret
                  key: DB_PASSWORD

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5