apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: farm-role
  namespace: farm

rules:
- apiGroups: [""]
  resources:
    - pods
    - services
    - configmaps

  verbs:
    - get
    - list
    - watch