apiVersion: v2

name: farm-stack

description: Farm Inventory Complete Platform

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:
  - name: farm-app
    version: 1.0.0
    repository: "file://charts/farm-app"

  - name: postgres
    version: 1.0.0
    repository: "file://charts/postgres"