---
# Source: farm-stack/charts/farm-app/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: farm-inventory-pdb

spec:
  maxUnavailable: 1

  selector:
    matchLabels:
      app: farm-inventory
---
# Source: farm-stack/charts/farm-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount

metadata:
  name: farm-service-account
---
# Source: farm-stack/charts/farm-app/templates/secret.yaml
apiVersion: v1
kind: Secret

metadata:
  name: farm-secret

type: Opaque

data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXMxMjM=
---
# Source: farm-stack/charts/postgres/templates/secret.yaml
apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret

type: Opaque

data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  POSTGRES_DB: ZmFybWRi
---
# Source: farm-stack/charts/farm-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap

metadata:
  name: farm-inventory-config

data:
  APP_NAME: "Farm Inventory"
  ENVIRONMENT: "Development"
  COMPANY: "Amjmax Solutions"

  DB_HOST: "postgres-service.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "farmdb"
---
# Source: farm-stack/charts/postgres/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi
---
# Source: farm-stack/charts/farm-app/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: farm-role

rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
---
# Source: farm-stack/charts/farm-app/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: farm-rolebinding

subjects:
  - kind: ServiceAccount
    name: farm-service-account

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: farm-role
---
# Source: farm-stack/charts/farm-app/templates/service.yaml
apiVersion: v1
kind: Service

metadata:
  name: farm-inventory-service

spec:
  type: NodePort

  selector:
    app: farm-inventory

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
---
# Source: farm-stack/charts/postgres/templates/service.yaml
apiVersion: v1
kind: Service

metadata:
  name: postgres-service

spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432

  type: ClusterIP
---
# Source: farm-stack/charts/farm-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: farm-inventory

spec:
  selector:
    matchLabels:
      app: farm-inventory

  template:
    metadata:
      labels:
        app: farm-inventory

    spec:
      serviceAccountName: farm-service-account

      containers:
        - name: farm-inventory

          image: "arjunmj/farm-stack:latest"

          imagePullPolicy: Always

          ports:
            - containerPort: 8000
          
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: APP_NAME

            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: ENVIRONMENT

            - name: COMPANY
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: COMPANY

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: farm-inventory-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: farm-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: farm-secret
                  key: DB_PASSWORD

          startupProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              memory: 128Mi
              cpu: 100m

            limits:
              memory: 256Mi
              cpu: 500m
---
# Source: farm-stack/charts/postgres/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:

        - name: postgres

          image: "postgres:17"

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          resources:
            requests:
              memory: 256Mi
              cpu: 100m

            limits:
              memory: 512Mi
              cpu: 500m
        

          readinessProbe:
            exec:
              command:
              - pg_isready
              - -U
              - postgres

            initialDelaySeconds: 10
            periodSeconds: 5
        
          livenessProbe:
            exec:
              command:
              - pg_isready
              - -U
              - postgres

            initialDelaySeconds: 30
            periodSeconds: 10


      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
# Source: farm-stack/charts/farm-app/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: farm-inventory-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: farm-inventory

  minReplicas: 2
  maxReplicas: 6

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0

      policies:
        - type: Percent
          value: 100
          periodSeconds: 15

    scaleDown:
      stabilizationWindowSeconds: 60

      policies:
        - type: Percent
          value: 50
          periodSeconds: 60

  metrics:
    - type: Resource
      resource:
        name: cpu

        target:
          type: Utilization
          averageUtilization: 70
---
# Source: farm-stack/charts/farm-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: farm-inventory-ingress

spec:
  ingressClassName: traefik

  rules:
    - host: farm-inventory.local

      http:
        paths:
          - path: /

            pathType: Prefix

            backend:
              service:
                name: farm-inventory-service

                port:
                  number: 8000
