{{- if .Values.hpa.enabled }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: farm-inventory-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: farm-inventory

  minReplicas: {{ .Values.hpa.stable.minReplicas }}
  maxReplicas: {{ .Values.hpa.stable.maxReplicas }}

  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.scaleUp.stabilizationWindowSeconds }}

      policies:
        - type: {{ .Values.hpa.scaleUp.policy.type }}
          value: {{ .Values.hpa.scaleUp.policy.value }}
          periodSeconds: {{ .Values.hpa.scaleUp.policy.periodSeconds }}

    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.scaleDown.stabilizationWindowSeconds }}

      policies:
        - type: {{ .Values.hpa.scaleDown.policy.type }}
          value: {{ .Values.hpa.scaleDown.policy.value }}
          periodSeconds: {{ .Values.hpa.scaleDown.policy.periodSeconds }}

  metrics:
    - type: Resource
      resource:
        name: cpu

        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.stable.cpuUtilization }}

{{- end }}