apiVersion: v1
kind: Service

metadata:
  name: farm-inventory-service
  labels:
    app: farm-inventory

spec:
  type: {{ .Values.service.type }}

  selector:
    app: farm-inventory
    color: {{ .Values.blueGreen.activateColor }}

  ports:
    - name: http 
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}