name: Farm Inventory CI

on:
  push:
    branches:
      - main
      - feature/inventory-api

jobs:
  
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build \
          -t arjunmj/farm-inventory:latest \
          -t arjunmj/farm-inventory:${{ github.run_number }} \
          -f docker/Dockerfile .

      - name: Verify Docker Image
        run: |
          docker images | grep farm-inventory


  security-scan:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: arjunmj/farm-inventory:latest
          format: table
          severity: HIGH,CRITICAL
          exit-code: 0


  push-image:
    runs-on: self-hosted
    needs: security-scan
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Images
        run: |
          docker push arjunmj/farm-inventory:latest
          docker push arjunmj/farm-inventory:${{ github.run_number }}
  
  deploy-k8s:
    runs-on: self-hosted
    needs: push-image

    env:
        KUBECONFIG: /home/devops/.kube/config
    steps:
      - name: Verify Kubernetes
        run: |
          kubectl get nodes
      
      - name: Show Image Tag
        run: |
           echo "Deploying image arjunmj/farm-inventory:${{ github.run_number }}"
      
      - name: Update Deployment Image
        run: |
          kubectl set image deployment/farm-inventory \
          farm-inventory=arjunmj/farm-inventory:${{ github.run_number }} \
          -n farm
      - name: Annotate Deployments
        run: |
          kubectl annotate deployments farm-inventory \
          kubernetes.io/change-cause="GitHub run ${{github.run_number}}" \
          -n farm --overwrite
      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/farm-inventory -n farm
  
  verify-deployment:
    runs-on: self-hosted
    needs: deploy-k8s

    env:
        KUBECONFIG: /home/devops/.kube/config
    steps:
      - name: verify pods 
        run: |
          kubectl get pods -n farm
      - name: Verify Deployments
        run: |
          kubectl get deployment -n farm
      - name: Verify Services
        run: |
          kubectl get svc -n farm
      - name: Verify Ingress
        run: |
          kubectl get ingress -n farm
      - name: Application Health Check
        run: |
          curl -H "Host: farm-inventory.local" \
          http://192.168.29.5/
  
  cleanup-dockerhub:
    needs: push-image
    runs-on: self-hosted

    steps:
    

    - name: Cleanup old Docker Hub tags
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        REPOSITORY: farm-inventory
      run: |

        TOKEN=$(curl -s \
          -H "Content-Type: application/json" \
          -X POST \
          -d "{\"username\":\"$DOCKER_USER\",\"password\":\"$DOCKER_TOKEN\"}" \
          https://hub.docker.com/v2/users/login/ \
          | jq -r .token)

        TAGS=$(curl -s \
          -H "Authorization: JWT $TOKEN" \
          "https://hub.docker.com/v2/repositories/$DOCKER_USER/$REPOSITORY/tags/?page_size=100" \
          | jq -r '.results[].name')

        OLD_TAGS=$(echo "$TAGS" \
          | grep -E '^[0-9]+$' \
          | sort -n \
          | head -n -15)

        for tag in $OLD_TAGS
        do
          echo "Deleting tag: $tag"

          curl -s -X DELETE \
            -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/$DOCKER_USER/$REPOSITORY/tags/$tag/"
        done            


      
      
    