name: Farm Inventory CI

on:
  push:
    branches:
      - main
      - feature/inventory-api

jobs:
  
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build \
          -t arjunmj/farm-inventory:latest \
          -t arjunmj/farm-inventory:${{ github.run_number }} \
          -f docker/Dockerfile .

      - name: Verify Docker Image
        run: |
          docker images | grep farm-inventory


  security-scan:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: arjunmj/farm-inventory:latest
          format: table
          severity: HIGH,CRITICAL
          exit-code: 0


  push-image:
    runs-on: self-hosted
    needs: security-scan
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Images
        run: |
          docker push arjunmj/farm-inventory:latest
          docker push arjunmj/farm-inventory:${{ github.run_number }}


  deploy-test:
    runs-on: self-hosted
    needs: push-image
    steps:
      - name: Remove Existing Container
        run: |
          docker rm -f farm-test || true

      - name: Run Container
        run: |
          docker run -d \
          --name farm-test \
          -p 8001:8000 \
          arjunmj/farm-inventory:latest

      - name: Container Debug
        run: |
          docker ps -a
          docker logs farm-test || true


  health-check:
    runs-on: self-hosted
    needs: deploy-test
    steps:
      - name: Verify Application
        run: |
          sleep 10
          curl http://192.168.29.5:8001/


  cleanup:
    runs-on: self-hosted
    needs: health-check
    if: always()
    steps:
      - name: Cleanup Container
        run: |
          docker rm -f farm-test || true

